services:
  app: #Тут название может быть любое, лучше как название папки у проекта
    build: ./app #Тут указывается где находится docker-file в проекте
    container_name: app #Имя контейнера, когда все запустится
    ports:
      - "3028:3028"
    volumes:
      - ./app:/app
      - /app/public
    depends_on: # Сервис будет запущен, только после старта mysql_db
      - mysql_db
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: Test
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2
    volumes:
      - /app/data
 